wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
batch:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    code_path: code/train_single_task.py
    python_version: 3.10.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716087709.830939
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.10
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
